apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    flux.weave.works/automated: "true"
  name: hello-world
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: hello-world
    spec:
      containers:
      - name: hello-world
        image: gcr.io/k8s-demos-142718/github-bboreham-hello-world-image:037893862d025a1a48cc98f37f215df66396473f
        ports:
        - containerPort: 80
