apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    flux.weave.works/automated: "true"
  name: hello-world
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: hello-world
    spec:
      containers:
      - name: hello-world
        image: gcr.io/k8s-demos-142718/github-bboreham-hello-world-image:419a3ddf7ce6e7f4f04197109771f410de688177
        ports:
        - containerPort: 80
