apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    flux.weave.works/automated: "true"
  name: hello-world
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: hello-world
    spec:
      containers:
      - name: hello-world
        image: gcr.io/k8s-demos-142718/github-bboreham-hello-world-image:e62f4556018614a8f4fc62e0d917358593a2e8ad
        ports:
        - containerPort: 80
