apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    flux.weave.works/automated: "true"
  name: hello-world
spec:
  replicas: 4
  template:
    metadata:
      labels:
        name: hello-world
    spec:
      containers:
      - name: hello-world
        image: gcr.io/k8s-demos-142718/github-bboreham-hello-world-image:c62e4fd3f729a9ead8edc102472fad3ebbf6ef2c
        ports:
        - containerPort: 80
