apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 30001
  selector:
    name: hello-world
                                                                                            
