apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: hello-world
    spec:
      containers:
      - name: hello-world
        image: gcr.io/k8s-demos-142718/github-bboreham-hello-world-image:51926c709974f25efd48a2fb461c215ea8d69308
        ports:
        - containerPort: 80
